### ISSUE TITLE
Modificacion contextos Sistra

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/sistra#402]
Numero: 19
Creació: 2016-03-07 08:04:23.451
Permitir establecer un contexto raiz y unificar los contextos segun directrices CAIB

**Comment by jsastre-dgtic** [comment]
1.- La filosofia genèrica és la que va descriure Serveis Web: Tot el que sigui accessible exclusivament només des de la intranet ha de ser BACK. Tot el que sigui accessible tant des de intranet com internet ha de ser FRONT. Tot això referit a un EAR.  Amb la peculiaritat del nostre cas, on tenim diversos mòduls a contemplar però encapsulat en un sol EAR, hem de definir exactament com quedaria tot. 
 
/sistraback/... (exclusiu entorn intranet)
/sistrafront/... (entorn internet)

2.- Concretament, i esperam no deixar-nos cap mòdul a contemplar, tendríem:

https://intranet.caib.es/redoseback/                 --> https://intranet.caib.es/sistraback/redose/ 
https://intranet.caib.es/formback/                 --> https://intranet.caib.es/sistraback/form/ 
https://intranet.caib.es/formadmin/                --> https://intranet.caib.es/sistraback/formadmin/ 
https://intranet.caib.es/bantelback/                 --> https://intranet.caib.es/sistraback/bantel/ 
https://intranet.caib.es/bantelfront/                --> https://intranet.caib.es/sistraback/safata/ *1* 
https://intranet.caib.es/sistraadmin/                --> https://intranet.caib.es/sistraback/sistraadmin/ 
https://intranet.caib.es/sistraback/                --> https://intranet.caib.es/sistraback/sistra/ 
https://intranet.caib.es/auditfront/                 --> https://intranet.caib.es/sistraback/audita/ 
https://intranet.caib.es/zonaperhelpdesk/        --> https://intranet.caib.es/sistraback/helpdesk/ 
https://intranet.caib.es/zonaperback/                 --> https://intranet.caib.es/sistraback/prereg/ 
https://intranet.caib.es/zonaperdelega/                --> https://intranet.caib.es/sistraback/respresentants/ ?? 
https://intranet.caib.es/pagosTPVBack/                --> https://intranet.caib.es/sistraback/pagaTPV 
https://intranet.caib.es/sistra/console/                --> https://intranet.caib.es/sistraback/consola/ 
https://intranet.caib.es/mobtratelback/                --> https://intranet.caib.es/sistraback/mobtratel/ 
https://intranet.caib.es/mobtratelfront/                --> https://intranet.caib.es/sistraback/enviamsg/ 

https://intranet.caib.es/sistraXXX/ws                -->?? 



8-regtel-ws.war                                -->?? 
1-audit-admin.war                                -->?? 
5-sistra-listar.war                                -->?? 

https://www.caib.es/zonaperfront/                --> https://www.caib.es/sistrafront/zonaper/ 
https://www.caib.es/sistrafront/                        --> https://www.caib.es/sistrafront/sistra 
https://www.caib.es/formfront/                        --> https://www.caib.es/sistrafront/form 


*1* Aquest mòdul ha de ser accessible des de fora. Hauríem de confirmar com està configurat el proxy-pass.
