### ISSUE TITLE
Permitir que la configuracion de SISTRA se espefique en un SAR

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/sistra#404]
Numero: 17
Creació: 2016-02-09 11:56:56.131
Permitir que la configuracion de SISTRA se espefique en un SAR

**Comment by jsastre-dgtic** [comment]
S'hauria d'avaluar simplement posar els .properties dins el sar i dir-li a l'aplicació que carregàs aquestes propietats (construït manualment el SAR tal com s’ofereixen els fitxers de propietats)

El desitjable i més pràctic, si la primera opció suposa molta càrrega, seria que la ruta dels fitxers .properties estigui definida dins una propietat de sistema. Això faria innecessària la incorporació de totes les properties dins un SAR (tant a jboss 3 com a 5 o 6) . 

Concretament:
Actualment la propietat de sistema on es defineix la ruta als fitxers de propietats d'aplicació està definida a sistra-properties.sar/META-INF/jboss-service.xml, el seu contingut és: 

<server> 
 <mbean code="org.jboss.varia.property.SystemPropertiesService" name="jboss:type=Service,name=sistraProperties"> 
   <attribute name="Properties"> 
       ad.path.properties=/app/caib/ 
       es.caib.sistra.valcert.username=SISTRA 
       es.caib.sistra.valcert.password=xxxx 
       es.caib.sistra.valcert.custodia.ws.URL=https://intranet.caib.es/signatura/services/CustodiaDocumentos 
   </attribute> 
  </mbean> 
</server> 

Possible millora: adoptar nomenclatura estàndar, i fer que la ruta indiqui exactament el directori on s'han de guardar els fitxers. (/app/caib/sistra): 

       es.caib.sistra.ad.path.properties=/app/caib/sistra (perque nomes s'ha de poder escriure dins el subdirectori especifics de l'aplicacio, en aquest cas sistra).
