### ISSUE TITLE
Problema de duplicación de números de registro en entorno de preproducción CAIB

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra#444]
Revisión de logs SISTRA del entorno de preproducción para diagnóstico de procesado con error de entradas de trámites UDIT.
- Comunicación con personal DGDT para la resolución del problema.
- Seguimiento del error.

**Comment by amaciam-indra** [comment]
Se comprueba que se resuelve el problema una vez actualizados los contadores del registro de entrada/salida del entorno
