### ISSUE TITLE
Correcció de literals i modificacions del formulari d’incidències

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra#509]
1. Des de les meves gestions, tenim un peu de pàgina amb una referència al Telèfon 012 (accés les meves gestions.jpg). Això va per properties? Quina? 
Sí, aquest peu de pàgina va per propietats. Aquesta propietat es la organismo.footer.contacto del global.properties.

2. A la mateixa imattge podem veure: Necessitau ajuda? Contacte amb l'equip de suport (Hauria de posar Contactau, no contacte) 
Ok, ho miram de canviar per la propera versió.

3. Si entram als tràmits sense enviar tenim un text que diu: En aquest apartat podeu reanudar ... (Hauria de dir reprendre, no reanudar) 
Ok, ho miram de canviar per la propera versió.

4. En aquesta pàgina (https://www.caib.es/sistrafront/zonaperfront/protected/tramitesSinEnviar.do) també tenim una referència al 012 al peu. Ídem punt 1 
Per aquest punt aplica la resposta al punt 1

5. En la pàgina de Tràmits enviats (https://www.caib.es/sistrafront/zonaperfront/protected/estadoExpedientes.do), tenim un text que diu: Para consultar el detalle de un trámite pulse sobre el título del trámite. Substituir-ho per "Per tal de consultar la seva tramitació, cliqui damunt el títol del tràmit. " 
Ok, ho miram de canviar per la propera versió.

6. Als correus que rebem els gestors provinents del formulari hi trobam a faltar 2 coses: 
        6.1. L'assumpte general de "Incidència tramitació" podria venir concatenat amb el Tipus de problema? Exemple:  "Incidència tramitació - Problemes amb el pagament" 
                Sí, es podría fer. Ho miram d’incorporar a la propera versió.

        6.2. Al detall del correu on es recull tota la informació podríem afegir el mètode d'entrada? (certificat/usuari/anònim) 
Sí, es podria mirar de capturar i incloure al mail. S’ha de tenir en compte que els plugins de pagament, ATIB i TPV, també tenen el formulari d’incidències i s’hauria d’establir el nivell d’autenticació. Això ho comentam més que res pel problema que s’ha detectat recentment, a partir de l’auditoria d’esdeveniments, de que no està arribant bé el Principal d’autenticació.

**Comment by jsastre-dgtic** [comment]
També quedaria el que comentàrem per corregir respecte del literal a les Meves Gestions: 

Corregir Literal: Canviar el literal que surt ara a les meves gestions quan has pagat però no registrat. 
En lloc de dir "Continuar amb el pagament" ha de dir "Continuar amb la tramitació" i quan boti a l'assistent de pagament ja veurem si ha de pagar encara o si ja ha paga.

**Comment by jsastre-dgtic** [comment]
Millora: que a l'assumpte surt el codi de tràmit:

Incidència tramitació - Dubtes funcionals - TS0010REGT

**Comment by amaciam-indra** [comment]
Ha hagut un error al missatge del commit que vincula amb la issue. La millora s'ha incorporat mitjançant el commit a114774
