### ISSUE TITLE
Missatge info a Les Meves Gestions

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra#523]
"És possible que tingui altres notificacions electròniques corresponents a tramitacions no gestionades des de l'assistent de tramitació telemàtica del Govern de les Illes Balears i que no es trobin a la seva disposició directament des d'aquí, "Les meves gestions" de la seu electrònica. Per accedir-hi, podeu fer-ho des de la Caprta Ciutadana del Punt d'Accés General de l'Estat  https://sede.administracion.gob.es/carpeta "

**Comment by amaciam-indra** [comment]
S'ha implementat la funcionalitat de manera que el text a mostrar es podrà configurar a nivell de properties (zonaper.properties), a través de les propietats notificaciones.noSistra.info._xx_, on _xx_ és el codi d'idioma (es, ca, etc.).
Aquest text únicament es mostrarà a "Les Meves Gestions" en cas d'accés autenticat, ja que no té sentit per accessos sense autenticació, ja que aquests tipus d'accessos sempre estAn vinculats a una tramitació telemàtica o a una notificació telemàtica generada des de SISTRA.
