### ISSUE TITLE
Canvi a RW3: Tipus d'assumpte "01 - Deprecated"

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra#537]
Adaptació a nivell de dades per establir en els tràmits que es faci servir el tipus d'assumpte "01 - Deprecated"

**Comment by dmadronal-indra** [comment]
Buenas, adjuntamos el script SQL a lanzar en el usuario SISTRA de BD del entorno a actualizar.
[sistra.sql.txt](https://github.com/GovernIB/sistra/files/3600518/sistra.sql.txt)
